/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system2020;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class administrar extends javax.swing.JFrame {

    DefaultTableModel model;
    Statement sent;

    /**
     * Creates new form administrar
     */
    public administrar() {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);

        txt_nombre_user.setEditable(false);
        txt_clave_user.setEditable(false);

        btn_modificar.setVisible(false);
        btn_confirmar_clave.setVisible(false);

        CargarUsuarios("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelVentas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PanelProductos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelUsuarios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nombre_user = new javax.swing.JTextField();
        txt_clave_user = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btn_cambiar_clave = new javax.swing.JButton();
        btn_confirmar_clave = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_nuevo = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_atras = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        id_usuario = new javax.swing.JLabel();
        tipo_usuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(830, 538));
        setUndecorated(true);

        fondo.setBackground(new java.awt.Color(204, 204, 255));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VENTAS REGISTRADAS");

        javax.swing.GroupLayout PanelVentasLayout = new javax.swing.GroupLayout(PanelVentas);
        PanelVentas.setLayout(PanelVentasLayout);
        PanelVentasLayout.setHorizontalGroup(
            PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelVentasLayout.setVerticalGroup(
            PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(375, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ventas", PanelVentas);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PRODUCTOS REGISTRADOS");

        javax.swing.GroupLayout PanelProductosLayout = new javax.swing.GroupLayout(PanelProductos);
        PanelProductos.setLayout(PanelProductosLayout);
        PanelProductosLayout.setHorizontalGroup(
            PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelProductosLayout.setVerticalGroup(
            PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(375, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Productos", PanelProductos);

        PanelUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USUARIOS REGISTRADOS");
        PanelUsuarios.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 744, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Usuarios:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)))); // NOI18N

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUsuarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        PanelUsuarios.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 390, 210));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setText("Clave:");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel6.setText("Tipo:");

        txt_nombre_user.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_clave_user.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Invitado", "Administrador" }));

        btn_cambiar_clave.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_cambiar_clave.setText("Cambiar Clave!");
        btn_cambiar_clave.setBorder(null);
        btn_cambiar_clave.setContentAreaFilled(false);
        btn_cambiar_clave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cambiar_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cambiar_claveActionPerformed(evt);
            }
        });

        btn_confirmar_clave.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_confirmar_clave.setText("Confirmar!");
        btn_confirmar_clave.setBorder(null);
        btn_confirmar_clave.setContentAreaFilled(false);
        btn_confirmar_clave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_confirmar_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmar_claveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombre_user, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_clave_user)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_cambiar_clave, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_confirmar_clave, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_nombre_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_clave_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cambiar_clave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_confirmar_clave)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        PanelUsuarios.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 260, 210));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 27, -1, -1));

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 27, -1, -1));

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 27, 70, -1));

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 27, -1, -1));

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 27, -1, -1));

        btn_modificar.setText("Actualizar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 27, -1, -1));

        PanelUsuarios.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 490, 70));

        jTabbedPane1.addTab("Usuarios", PanelUsuarios);

        btn_atras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_atras.setText("ATRÁS");
        btn_atras.setMaximumSize(new java.awt.Dimension(105, 23));
        btn_atras.setMinimumSize(new java.awt.Dimension(105, 23));
        btn_atras.setPreferredSize(new java.awt.Dimension(105, 23));
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BOTONES/CANDADO.png"))); // NOI18N
        jButton1.setText("Cerrar Sesión");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        id_usuario.setFont(new java.awt.Font("Calibri", 2, 11)); // NOI18N
        id_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id_usuario.setText("usuario");

        tipo_usuario.setFont(new java.awt.Font("Calibri", 2, 11)); // NOI18N
        tipo_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipo_usuario.setText("tipo");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(fondoLayout.createSequentialGroup()
                            .addComponent(btn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(id_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_usuario)
                    .addComponent(tipo_usuario))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void CargarUsuarios(String valor) {
        try {
            String[] titulos = {"ID", "Nombre", "Clave", "Tipo"};
            String[] registros = new String[5];
            String sql = "SELECT * FROM usuarios where id LIKE '%" + valor + "%' ";
            model = new DefaultTableModel(null, titulos);
            sent = cn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("id");
                registros[1] = rs.getString("nombre_usuario");
                registros[2] = rs.getString("clave_usuario");
                registros[3] = rs.getString("tipo_usuario");

                model.addRow(registros);
            }
            jTableUsuarios.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void guardar_usuario() {
        if (txt_nombre_user.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falta *Nombre de Usuario*", "Completar Información", 1);
            txt_nombre_user.grabFocus();
        } else if (txt_clave_user.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falta *Clave de Usuario*", "Completar Información", 1);
            txt_clave_user.grabFocus();
        } else if (jComboBox1.getSelectedItem().equals("Seleccione")) {
            JOptionPane.showMessageDialog(null, "Falta *Tipo de Usuario*", "Completar Información", 1);
            jComboBox1.grabFocus();
        } else {
            String tNombre, tClave, tTipo;
            String sql = "";
            tNombre = txt_nombre_user.getText();
            tClave = txt_clave_user.getText();
            tTipo = jComboBox1.getActionCommand();

            sql = "INSERT INTO usuarios(nombre_usuario, clave_usuario, tipo_usuario) VALUES(?,?,?)";
            try {
                PreparedStatement pst = cn.prepareCall(sql);

                pst.setString(1, tNombre);
                pst.setString(2, tClave);
                pst.setString(3, jComboBox1.getSelectedItem().toString());

                int n = pst.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(null, "* Usuario Registrado *", "Operación Exitosa", 1);
                }
            } catch (SQLException ex) {
                Logger.getLogger(procesar_pago.class.getName()).log(Level.SEVERE, null, ex);
            }
            CargarUsuarios("");

            txt_nombre_user.setEditable(false);
            txt_clave_user.setEditable(false);

            btn_editar.setVisible(true);
            btn_modificar.setVisible(false);

            btn_nuevo.setEnabled(true);
            btn_guardar.setEnabled(true);
            btn_editar.setEnabled(true);
            btn_eliminar.setEnabled(true);

            txt_nombre_user.setText("");
            txt_clave_user.setText("");
            jComboBox1.setSelectedItem("Seleccione");

        }
    }

    public void registrar_usuario() {
        String regist;
        String sql = ("");
        String exp = txt_nombre_user.getText();

        boolean existe = false; //variable bandera para comprobar si NO existe el expediente en la BD

        try {
            sql = "SELECT * FROM usuarios WHERE nombre_usuario = '" + exp + "'";

            ResultSet rs = sent.executeQuery(sql);

            while (rs.next()) {
                existe = true;
                if (existe == true) {
                    regist = rs.getString("nombre_usuario");
                    if (exp.equals(regist)) {
                        JOptionPane.showMessageDialog(null, "El Usuario: " + regist + " Ya Está Registrado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                        txt_nombre_user.setText("");
                        txt_nombre_user.grabFocus();
                    }
                }
            }//fin while res.next
            if (existe == false) {
                guardar_usuario();
            }
            rs.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void cancelar() {
        txt_nombre_user.setEditable(false);
        txt_clave_user.setEditable(false);

        btn_editar.setVisible(true);
        btn_modificar.setVisible(false);
        btn_cambiar_clave.setVisible(true);
        btn_confirmar_clave.setVisible(false);

        btn_nuevo.setEnabled(true);
        btn_guardar.setEnabled(true);
        btn_editar.setEnabled(true);
        btn_eliminar.setEnabled(true);

        txt_nombre_user.setText("");
        txt_clave_user.setText("");
        jComboBox1.setSelectedItem("Seleccione");
        jComboBox1.setEnabled(true);
    }

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        int sal = JOptionPane.showConfirmDialog(null, "Desea Cancelar El Ingreso?", "Confirme Opción", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (sal == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login1 log = new login1();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        txt_nombre_user.setEditable(true);
        txt_clave_user.setEditable(true);
        txt_nombre_user.grabFocus();

        btn_nuevo.setEnabled(false);
        btn_editar.setEnabled(false);
        btn_eliminar.setEnabled(false);
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        if (txt_nombre_user.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Seleccione Algún Registro Para Editar", "Alerta", JOptionPane.ERROR_MESSAGE);
        } else {

            txt_nombre_user.setEditable(true);
            txt_clave_user.setEditable(true);

            btn_editar.setVisible(false);
            btn_modificar.setVisible(true);

            btn_guardar.setEnabled(false);

            txt_nombre_user.grabFocus();
    }//GEN-LAST:event_btn_editarActionPerformed
    }

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        registrar_usuario();
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void jTableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuariosMouseClicked
        if (evt.getButton() == 1) {
            int pst = jTableUsuarios.getSelectedRow();
            try {
                String sql = "SELECT * FROM usuarios WHERE id= " + jTableUsuarios.getValueAt(pst, 0).toString();
                sent = cn.createStatement();
                ResultSet rs = sent.executeQuery(sql);
                rs.next();
                txt_nombre_user.setText(rs.getString("nombre_usuario"));
                txt_clave_user.setText(rs.getString("clave_usuario"));
                jComboBox1.setSelectedItem(rs.getString("tipo_usuario"));

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        //txt_cantidad.grabFocus();
    }//GEN-LAST:event_jTableUsuariosMouseClicked

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        String regist;
        String sql = ("");
        String exp = txt_nombre_user.getText();

        boolean existe = false; //variable bandera para comprobar si NO existe el expediente en la BD

        try {
            sql = "SELECT * FROM usuarios WHERE nombre_usuario = '" + exp + "'";

            ResultSet rs = sent.executeQuery(sql);

            while (rs.next()) {
                existe = true;
                if (existe == true) {
                    regist = rs.getString("nombre_usuario");
                    if (exp.equals(regist)) {
                        JOptionPane.showMessageDialog(null, "" + regist + "  YA EXISTE", "Mensaje", JOptionPane.ERROR_MESSAGE);
                        cancelar();
                        txt_nombre_user.grabFocus();

                    }
                }
            } //fin while res.next
            if (existe == false) {
                if (txt_nombre_user.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Ha Dejado el Campo 'Nombre' Vacio", "aviso", JOptionPane.ERROR_MESSAGE);
                } else if (txt_clave_user.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Ha Dejado el Campo 'Clave' Vacio", "aviso", JOptionPane.ERROR_MESSAGE);
                } else if (jComboBox1.getSelectedItem().equals("Seleccione...")) {
                    JOptionPane.showMessageDialog(null, "Ha Dejado el Campo 'Tipo' Vacio", "aviso", JOptionPane.ERROR_MESSAGE);
                } else {

                    String nom, cla, tip;

                    nom = txt_nombre_user.getText();
                    cla = txt_clave_user.getText();
                    tip = (String) jComboBox1.getSelectedItem();

                    try {
                        sql = "Update usuarios set nombre_usuario=?, clave_usuario=?, tipo_usuario=?"
                                + "where id=?";
                        int fila = jTableUsuarios.getSelectedRow();
                        String dao = (String) jTableUsuarios.getValueAt(fila, 0);
                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.setString(1, nom);
                        pst.setString(2, cla);
                        pst.setString(3, tip);

                        pst.setString(4, dao);

                        int n = pst.executeUpdate();
                        if (n > 0) {
                            JOptionPane.showMessageDialog(null, "Registro Modificado");

                        }
                        CargarUsuarios("");
                        cancelar();

                    } catch (HeadlessException | SQLException e) {

                    }
                }
            }
            rs.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_cambiar_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cambiar_claveActionPerformed
        if (txt_nombre_user.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Seleccione Algún Usuario para Modificar", "Alerta", JOptionPane.ERROR_MESSAGE);
        } else {
            txt_nombre_user.setEditable(false);
            txt_clave_user.setEditable(true);
            txt_clave_user.grabFocus();
            jComboBox1.setEnabled(false);
            btn_editar.setEnabled(false);
            btn_cambiar_clave.setVisible(false);
            btn_confirmar_clave.setVisible(true);

        }
    }//GEN-LAST:event_btn_cambiar_claveActionPerformed

    private void btn_confirmar_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmar_claveActionPerformed
        if (txt_clave_user.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ha Dejado el Campo 'Clave' Vacio", "aviso", JOptionPane.ERROR_MESSAGE);
            txt_clave_user.grabFocus();
        } else {

            String nom, cla, tip;
            String sql = ("");

            nom = txt_nombre_user.getText();
            cla = txt_clave_user.getText();
            tip = (String) jComboBox1.getSelectedItem();

            try {
                sql = "Update usuarios set nombre_usuario=?, clave_usuario=?, tipo_usuario=?"
                        + "where id=?";
                int fila = jTableUsuarios.getSelectedRow();
                String dao = (String) jTableUsuarios.getValueAt(fila, 0);
                PreparedStatement pst = cn.prepareStatement(sql);
                pst.setString(1, nom);
                pst.setString(2, cla);
                pst.setString(3, tip);

                pst.setString(4, dao);

                int n = pst.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(null, "Contraseña Modificada");

                }
                CargarUsuarios("");
                cancelar();
                btn_atras.grabFocus();

            } catch (HeadlessException | SQLException e) {

            }
        }

    }//GEN-LAST:event_btn_confirmar_claveActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        if (txt_nombre_user.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Seleccione un Registro...", "aviso", JOptionPane.ERROR_MESSAGE);
        } else {

            int sal = JOptionPane.showConfirmDialog(null, "Desea Eliminar Usuario Seleccionado?", "Confirme Opción", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (sal == 0) {
                try {

                    int fila = jTableUsuarios.getSelectedRow();
                    String sql = "delete from usuarios where id = " + jTableUsuarios.getValueAt(fila, 0);
                    sent = cn.createStatement();
                    int n = sent.executeUpdate(sql);
                    if (n > 0) {

                    }

                    CargarUsuarios("");
                    cancelar();

                } catch (SQLException | HeadlessException e) {
                    JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelProductos;
    private javax.swing.JPanel PanelUsuarios;
    private javax.swing.JPanel PanelVentas;
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_cambiar_clave;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_confirmar_clave;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JPanel fondo;
    public static javax.swing.JLabel id_usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableUsuarios;
    public static javax.swing.JLabel tipo_usuario;
    private javax.swing.JTextField txt_clave_user;
    private javax.swing.JTextField txt_nombre_user;
    // End of variables declaration//GEN-END:variables
    conectarBD cc = new conectarBD();
    Connection cn = cc.conexion();
}
