/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system2020;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author LENOVO
 */
public class descontar extends javax.swing.JFrame {

    /**
     * Creates new form descontar
     */
    public descontar() {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
        
        jSpDescuento.grabFocus();
        txtDiferencia.setVisible(false);

        //modelo para instanciar el Spinner
        SpinnerNumberModel nm = new SpinnerNumberModel();
        nm.setMaximum(100);
        nm.setMinimum(0);
        nm.setStepSize(5);
        jSpDescuento.setModel(nm);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipo_de_pago = new javax.swing.ButtonGroup();
        jPanel_informacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSpDescuento = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        txtMontoFinal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtConcepto = new javax.swing.JTextField();
        lblDiferencia = new javax.swing.JLabel();
        txtDiferencia = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        txtPago = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_informacion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "INFORMACIÓN DEL DESCUENTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Cliente:");

        txtCliente.setEditable(false);
        txtCliente.setFocusable(false);
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha:");

        txtFecha.setEditable(false);
        txtFecha.setFocusable(false);

        jLabel3.setText("Pago:");

        jLabel4.setText("Monto:");

        txtMonto.setEditable(false);
        txtMonto.setFocusable(false);

        jLabel5.setText("% Descuento:");

        jSpDescuento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpDescuentoStateChanged(evt);
            }
        });
        jSpDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpDescuentoKeyPressed(evt);
            }
        });

        jLabel6.setText("Monto Final:");

        txtMontoFinal.setEditable(false);
        txtMontoFinal.setFocusable(false);

        jLabel7.setText("Concepto:");

        btn_aceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_aceptar.setText("ACEPTAR");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        txtPago.setEditable(false);

        javax.swing.GroupLayout jPanel_informacionLayout = new javax.swing.GroupLayout(jPanel_informacion);
        jPanel_informacion.setLayout(jPanel_informacionLayout);
        jPanel_informacionLayout.setHorizontalGroup(
            jPanel_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_informacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(txtCliente)
                    .addComponent(jLabel5)
                    .addComponent(txtDiferencia))
                .addGap(36, 36, 36)
                .addGroup(jPanel_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtMontoFinal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel6)
                    .addComponent(lblDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addGroup(jPanel_informacionLayout.createSequentialGroup()
                            .addGroup(jPanel_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMonto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(46, 46, 46))
                        .addComponent(txtConcepto))
                    .addComponent(btn_aceptar))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel_informacionLayout.setVerticalGroup(
            jPanel_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_informacionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_informacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_informacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void caldular_descuento() {
        double n1, n2, n3, n4, nt;

        String num1X, num2X, num3X;
        String resultadoX, resultadoY;

        num1X = txtMonto.getText();
        num2X = jSpDescuento.getValue().toString();

        n1 = Double.parseDouble(num1X);
        n2 = Double.parseDouble(num2X);

        n3 = (n2 / 100);
        n4 = (n1 * n3);
        nt = (n1 - n4);

        resultadoX = String.valueOf(nt);
        resultadoY = String.valueOf(n4);
        txtMontoFinal.setText(resultadoX);
        //Evento para mostrar el valor del descuento al cambiar el spinner
        lblDiferencia.setText("Ahorro = " + resultadoY);
        txtDiferencia.setText(resultadoY);
        
        txtConcepto.grabFocus();
    }
    
    public void guardar_descuento() {
        if (jSpDescuento.getValue().toString().equals("0")) {
            JOptionPane.showMessageDialog(null, "Seleccione % de Descuento", "Completar Información", 1);
            jSpDescuento.grabFocus();
        } else if(txtConcepto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falta Detalles del Descuento", "Completar Información", 1);
            txtConcepto.grabFocus();
            
        } else {
            String tCliente, tFecha, tSubtotal, tPorciento, tDescuento, tTotal, tConcepto;
            String sql = "";
            tCliente = txtCliente.getText();
            tFecha = txtFecha.getText();
            tSubtotal = txtMonto.getText();
            tPorciento = jSpDescuento.getValue().toString();
            tDescuento = txtDiferencia.getText();
            tTotal = txtMontoFinal.getText();
            tConcepto = txtConcepto.getText();
            
            sql = "INSERT INTO descuentos(cliente, fecha, sub_total, porciento, descuento, total, concepto) VALUES(?,?,?,?,?,?,?)";
            try {
                PreparedStatement pst = cn.prepareCall(sql);

                pst.setString(1, tCliente);
                pst.setString(2, tFecha);
                pst.setString(3, tSubtotal);
                pst.setString(4, tPorciento);
                pst.setString(5, tDescuento);
                pst.setString(6, tTotal);
                pst.setString(7, tConcepto);
                int n = pst.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(null, "* DESCUENTO REGISTRADO *", "Operación Exitosa", 1);
                }
            } catch (SQLException ex) {
                Logger.getLogger(procesar_pago.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            String n_montofinal = txtMontoFinal.getText();
            procesar_pago.txt_total.setText(n_montofinal);
            String n_descuento = txtDiferencia.getText();
            procesar_pago.txt_descuento.setText(n_descuento);
    
            this.setVisible(false);
            
        }
    }
    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void jSpDescuentoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpDescuentoStateChanged
    caldular_descuento();    
    
    }//GEN-LAST:event_jSpDescuentoStateChanged

    private void jSpDescuentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpDescuentoKeyPressed
    caldular_descuento();
    }//GEN-LAST:event_jSpDescuentoKeyPressed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
    
    guardar_descuento();
    }//GEN-LAST:event_btn_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(descontar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(descontar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(descontar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(descontar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new descontar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel_informacion;
    private javax.swing.JSpinner jSpDescuento;
    private javax.swing.JLabel lblDiferencia;
    private javax.swing.ButtonGroup tipo_de_pago;
    public static javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtConcepto;
    private javax.swing.JTextField txtDiferencia;
    public static javax.swing.JTextField txtFecha;
    public static javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtMontoFinal;
    public static javax.swing.JTextField txtPago;
    // End of variables declaration//GEN-END:variables
conectarBD cc = new conectarBD();
Connection cn = cc.conexion();
}
