/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system2020;

import Animacion.Fade;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Programa
 */
public class mozo extends javax.swing.JFrame implements Runnable {

    String hora, minuto, segundo; // variables para la hora
    Thread hilo;
    //Instancia de la Base de Datos
    DefaultTableModel model, modelo;
    Statement sent;
    CallableStatement cst;

    /**
     * Creates new form principal
     */
    public mozo() {
        initComponents();
        this.setTitle("System2020 - Registro de Ventas"); // titulo de la ventana
        this.setResizable(false); // desactivar maximizar ventana
        setLocationRelativeTo(null); // centrar la ventana
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/home.png"));
        this.setIconImage(ico); // para asignar icono a la ventana
        busca_codigo.grabFocus(); // situar cursor en el jTextfile
        jlbfecha.setText(capturafecha()); // muestra la fecha capturada
        hilo = new Thread(this); // hilo para controlar la hora
        hilo.start();
        monto.setVisible(false);
        hora_pedido.setVisible(false);
        fecha_pedido.setVisible(false);
        codigo_producto.setVisible(false);
        stock_producto.setVisible(false);
        //des_producto_precio();
        //tabla_pedido();

        // ir a Customize Code para crear el metodo que permite desactivar la edición de celdas, en Propiedades, TableHead están las opciones para modificar el tamaño de la celda y reordenar las columnas, en Propiedades, opción focusable para eliminar el borde que se marca al hacer click en la celda.
        modelo = new DefaultTableModel();// Crea columnas para tabla del consumo de la mesa
        modelo.addColumn("Cantidad");
        modelo.addColumn("Nombre");
        modelo.addColumn("Monto");
        modelo.addColumn("Codigo");
        modelo.addColumn("Hora");
        modelo.addColumn("Fecha");
        modelo.addColumn("Vendedor");
        this.jTableMesaConsumo.setModel(modelo);

        jPanelSlider1.setVisible(false);
        baja.setVisible(false);

        // abre la ventana para procesar el pago
        procesar_pago abrir = new procesar_pago();
        abrir.setVisible(false);
        //
    }

    public void Hora() { // metodo para capturar la hora
        Calendar calendario = new GregorianCalendar();
        Date Hora = new Date();
        calendario.setTime(Hora);
        hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        minuto = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundo = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }

    public void run() { //metodo para correr y mostrar la hora
        Thread current = Thread.currentThread();
        while (current == hilo) {
            Hora();
            jlbhora.setText(hora + ":" + minuto + ":" + segundo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        nombre_producto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cantidad_producto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        precio_producto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        codigo_producto = new javax.swing.JTextField();
        busca_codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        agrega_producto = new javax.swing.JButton();
        limpia_producto = new javax.swing.JButton();
        monto = new javax.swing.JTextField();
        stock_producto = new javax.swing.JTextField();
        hora_pedido = new javax.swing.JTextField();
        jlbfecha = new javax.swing.JLabel();
        jlbhora = new javax.swing.JLabel();
        jPconsumo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMesaConsumo = new javax.swing.JTable();
        grabar1 = new javax.swing.JButton();
        eliminar1 = new javax.swing.JButton();
        vaciar = new javax.swing.JButton();
        subtotal = new javax.swing.JLabel();
        filas = new javax.swing.JLabel();
        jPproductos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        busca_todo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fecha_pedido = new javax.swing.JTextField();
        sube = new javax.swing.JButton();
        baja = new javax.swing.JButton();
        jPanelSlider1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        panel_open = new javax.swing.JPanel();
        btn_salir = new javax.swing.JButton();
        btn_devolucion = new javax.swing.JButton();
        btn_stock = new javax.swing.JButton();
        btn_gastar = new javax.swing.JButton();
        btn_carta = new javax.swing.JButton();
        btn_administrar = new javax.swing.JButton();
        btn_cerrars = new javax.swing.JButton();
        panel_close = new javax.swing.JPanel();
        usuario = new javax.swing.JLabel();
        usuario_tipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(960, 630));
        setMinimumSize(new java.awt.Dimension(960, 630));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1080, 590));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), " Pedido: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre_producto.setEditable(false);
        nombre_producto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(nombre_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Cantidad:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 70, -1));

        cantidad_producto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cantidad_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidad_productoKeyPressed(evt);
            }
        });
        jPanel2.add(cantidad_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 80, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Precio:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 70, -1));

        precio_producto.setEditable(false);
        precio_producto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(precio_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 70, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Producto:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 70, -1));

        codigo_producto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        codigo_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codigo_productoMouseClicked(evt);
            }
        });
        codigo_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigo_productoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigo_productoKeyReleased(evt);
            }
        });
        jPanel2.add(codigo_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 80, 30));

        busca_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busca_codigoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                busca_codigoKeyReleased(evt);
            }
        });
        jPanel2.add(busca_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 70, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Codigo:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, -1));

        agrega_producto.setText("Agg");
        agrega_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agrega_productoActionPerformed(evt);
            }
        });
        agrega_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                agrega_productoKeyPressed(evt);
            }
        });
        jPanel2.add(agrega_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 60, 40));

        limpia_producto.setText("Limp");
        limpia_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpia_productoActionPerformed(evt);
            }
        });
        limpia_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                limpia_productoKeyPressed(evt);
            }
        });
        jPanel2.add(limpia_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 60, 40));

        monto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 80, 30));

        stock_producto.setEditable(false);
        jPanel2.add(stock_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 170, 50, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 500, 200));
        getContentPane().add(hora_pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, 60, -1));

        jlbfecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jlbfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 540, 70, 20));

        jlbhora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jlbhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 520, 70, 20));

        jPconsumo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), " Consumo ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14)))); // NOI18N
        jPconsumo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableMesaConsumo = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTableMesaConsumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableMesaConsumo.setFocusable(false);
        jTableMesaConsumo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableMesaConsumo);

        jPconsumo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 930, 170));

        grabar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        grabar1.setText("SIGUIENTE");
        grabar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabar1ActionPerformed(evt);
            }
        });
        jPconsumo.add(grabar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 215, -1, -1));

        eliminar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        eliminar1.setText("ELIMINAR");
        eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar1ActionPerformed(evt);
            }
        });
        jPconsumo.add(eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 215, -1, -1));

        vaciar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vaciar.setText("VACIAR");
        vaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaciarActionPerformed(evt);
            }
        });
        jPconsumo.add(vaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 215, -1, -1));

        subtotal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        subtotal.setText("$SubT");
        jPconsumo.add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, 60, 30));

        filas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        filas.setText("Nº Filas");
        jPconsumo.add(filas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 50, 30));

        getContentPane().add(jPconsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 250, 1010, 260));

        jPproductos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), " Buscar Producto ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPproductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableProductos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableProductos.setFocusable(false);
        jTableProductos.getTableHeader().setReorderingAllowed(false);
        jTableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableProductos);

        jPproductos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 460, 110));

        busca_todo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busca_todoMouseClicked(evt);
            }
        });
        busca_todo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busca_todoKeyPressed(evt);
            }
        });
        jPproductos.add(busca_todo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel2.setText("(ingresa el nombre ó codigo)");
        jPproductos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 180, 30));

        getContentPane().add(jPproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 500, 200));
        getContentPane().add(fecha_pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 510, 60, -1));

        sube.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sube.setText(">");
        sube.setBorder(null);
        sube.setBorderPainted(false);
        sube.setContentAreaFilled(false);
        sube.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subeActionPerformed(evt);
            }
        });
        getContentPane().add(sube, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 50, 20));

        baja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        baja.setText("<");
        baja.setBorder(null);
        baja.setBorderPainted(false);
        baja.setContentAreaFilled(false);
        baja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaActionPerformed(evt);
            }
        });
        getContentPane().add(baja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 50, 20));

        jPanelSlider1.setBorder(null);

        panel_open.setLayout(new java.awt.GridLayout(1, 0));

        btn_salir.setText("Salir.");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        panel_open.add(btn_salir);

        btn_devolucion.setText("Ventas / Devolución");
        btn_devolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_devolucionActionPerformed(evt);
            }
        });
        panel_open.add(btn_devolucion);

        btn_stock.setText("Agregar Stock.");
        btn_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stockActionPerformed(evt);
            }
        });
        panel_open.add(btn_stock);

        btn_gastar.setText("Pagár Servicio.");
        btn_gastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gastarActionPerformed(evt);
            }
        });
        panel_open.add(btn_gastar);

        btn_carta.setText("Ver Cajero");
        panel_open.add(btn_carta);

        btn_administrar.setText("Administrar");
        btn_administrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_administrarActionPerformed(evt);
            }
        });
        panel_open.add(btn_administrar);

        btn_cerrars.setText("Cerrar Sesión.");
        btn_cerrars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarsActionPerformed(evt);
            }
        });
        panel_open.add(btn_cerrars);

        jPanelSlider1.add(panel_open, "card3");
        jPanelSlider1.add(panel_close, "card2");

        getContentPane().add(jPanelSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 830, 50));

        usuario.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuario.setText("usuario");
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 560, 70, 20));

        usuario_tipo.setText("usuario_tipo");
        getContentPane().add(usuario_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 560, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String capturafecha() { //metodo para capturar la fecha del sistema operativo
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YY");
        return formatoFecha.format(fecha);
    }

    public void limpia_pedido() {
        codigo_producto.setText(null);
        nombre_producto.setText(null);
        cantidad_producto.setText(null);
        precio_producto.setText(null);
        busca_todo.setText(null);
        codigo_producto.setVisible(false);
        busca_codigo.setVisible(true);

    }

    public void limpia_busqueda() {
        codigo_producto.setText(null);
        nombre_producto.setText(null);
        cantidad_producto.setText(null);
        precio_producto.setText(null);
        busca_codigo.setText(null);
        busca_todo.setText(null);
        stock_producto.setText(null);

    }

    public void des_producto_precio() {
        nombre_producto.setEnabled(false);
        precio_producto.setEnabled(false);
    }

    public void des_producto_entero() {
        codigo_producto.setEnabled(false);
        nombre_producto.setEnabled(false);
        precio_producto.setEnabled(false);
    }

    public void hab_producto() {
        nombre_producto.setEnabled(true);
    }

    public void agregar() {

        busca_codigo.requestFocus();
        hora_pedido.setText(jlbhora.getText());//covierte la hora de jlabel a jtextfile
        fecha_pedido.setText(jlbfecha.getText());
        // calcula precio * cantidad, Y compara la cantidad con el stock
        int num1, stock1;
        double num2, num3;

        String num1X, num2X, num_stock;
        String resultadoX;
        num1X = cantidad_producto.getText();
        num2X = precio_producto.getText();
        num_stock = stock_producto.getText();

        num1 = Integer.parseInt(num1X);
        num2 = Double.parseDouble(num2X);
        stock1 = Integer.parseInt(num_stock);
        num3 = (num1 * num2);

        if (num1 > stock1) {
            JOptionPane.showMessageDialog(null, "La cantidad deseada es superiór al stock disponible", "Importante", 1);
        } else {

            resultadoX = String.valueOf(num3);

            monto.setText(resultadoX);
            // cierra el calculo
            String[] info = new String[7];
            info[0] = cantidad_producto.getText();
            info[1] = nombre_producto.getText();
            info[2] = monto.getText();
            info[3] = codigo_producto.getText();
            info[4] = hora_pedido.getText();
            info[5] = fecha_pedido.getText();
            info[6] = usuario.getText();
            modelo.addRow(info);

            cantidad_producto.setText("");
            nombre_producto.setText("");
            codigo_producto.setText("");
            precio_producto.setText("");
            monto.setText("");
            busca_todo.setText("");
            hora_pedido.setText("");
            fecha_pedido.setText("");

            suma_montos();
            contar_filas();
            codigo_producto.setVisible(false);
            busca_codigo.setVisible(true);
            busca_codigo.grabFocus();
        }
    }

    public void suma_montos() {
        //suma las cantidades de una columna
        double fil = 0;
        double subt = 0;
        for (int i = 0; i < jTableMesaConsumo.getRowCount(); i++) {
            fil = Double.parseDouble(jTableMesaConsumo.getValueAt(i, 2).toString());
            subt += fil;

        }
        subtotal.setText("" + subt);
    }

    private void codigo_productoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigo_productoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            cantidad_producto.requestFocus();
        }
        //CargarProductos(busca_producto.getText());     
    }//GEN-LAST:event_codigo_productoKeyPressed

    private void limpia_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpia_productoActionPerformed
        limpia_pedido();
        nombre_producto.setEnabled(false);
        busca_codigo.grabFocus();
    }//GEN-LAST:event_limpia_productoActionPerformed

    private void cantidad_productoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad_productoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            agrega_producto.requestFocus();
        }
    }//GEN-LAST:event_cantidad_productoKeyPressed

    private void agrega_productoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agrega_productoKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER) {
            if (nombre_producto.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Indique El Producto", "aviso", 1);

            } else if (cantidad_producto.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Indique Cantidad Deseada", "aviso", 1);
            } else {
                agregar();
            }
        }
    }//GEN-LAST:event_agrega_productoKeyPressed

    private void limpia_productoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_limpia_productoKeyPressed
        if (evt.getKeyCode() == evt.VK_LEFT) {
            busca_codigo.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            agrega_producto.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_limpia_productoKeyPressed

    private void agrega_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agrega_productoActionPerformed
        if (nombre_producto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Indique El Producto", "aviso", 1);
        } else if (cantidad_producto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Indique Cantidad Deseada", "aviso", 1);
        } else {
            agregar();
        }
    }//GEN-LAST:event_agrega_productoActionPerformed

    private void btn_cerrarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarsActionPerformed

    }//GEN-LAST:event_btn_cerrarsActionPerformed

    private void jTableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosMouseClicked
        if (evt.getButton() == 1) {
            int pst = jTableProductos.getSelectedRow();
            try {
                String sql = "SELECT * FROM productos where codigo= " + jTableProductos.getValueAt(pst, 0).toString();
                sent = cn.createStatement();
                ResultSet rs = sent.executeQuery(sql);
                rs.next();
                codigo_producto.setVisible(true);
                codigo_producto.setText(rs.getString("codigo"));
                nombre_producto.setText(rs.getString("nombre"));
                precio_producto.setText(rs.getString("precio"));
                stock_producto.setText(rs.getString("stock"));
                //busca_codigo.setText(rs.getString("codigo"));

                des_producto_entero();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        cantidad_producto.grabFocus();
    }//GEN-LAST:event_jTableProductosMouseClicked
    void CargarProductos(String valor) {
        try {
            String[] titulos = {"id", "codigo", "nombre", "precio", "stock"};
            String[] registros = new String[5];
            String sql = "SELECT * FROM productos where codigo LIKE '%" + valor + "%' ";
            model = new DefaultTableModel(null, titulos);
            sent = cn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("id");
                registros[1] = rs.getString("codigo");
                registros[2] = rs.getString("nombre");
                registros[3] = rs.getString("precio");
                registros[4] = rs.getString("stock");

                model.addRow(registros);
            }
            jTableProductos.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void contar_filas() {
        for (int i = 0; i <= jTableMesaConsumo.getRowCount(); i++) {
            filas.setText("" + i);
        }
    }

    private void codigo_productoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigo_productoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_codigo_productoKeyReleased

    private void busca_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busca_codigoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            try {
                PreparedStatement consulta = cn.prepareStatement("SELECT * FROM productos where codigo=?");
                String b = busca_codigo.getText();

                consulta.setString(1, b);

                sent = cn.createStatement();
                ResultSet rs = consulta.executeQuery();

                if (rs.next()) {
                    busca_codigo.setVisible(false);
                    codigo_producto.setVisible(true);

                    nombre_producto.setText(rs.getString("nombre"));
                    codigo_producto.setText(rs.getString("codigo"));
                    precio_producto.setText(rs.getString("precio"));
                    stock_producto.setText(rs.getString("stock"));

                    cantidad_producto.grabFocus();
                    busca_codigo.setText("");

                } else {
                    nombre_producto.setText("");
                    codigo_producto.setText("");
                    precio_producto.setText("");
                }

            } catch (SQLException e) {

                JOptionPane.showMessageDialog(null, e.toString());

            }        // TODO add your handling code here:
    }//GEN-LAST:event_busca_codigoKeyPressed
    }
    private void busca_codigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busca_codigoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_busca_codigoKeyReleased

    private void codigo_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigo_productoMouseClicked
        nombre_producto.setText("");
        cantidad_producto.setText("");
        precio_producto.setText("");
        stock_producto.setText("");

        codigo_producto.setVisible(false);
        busca_codigo.setVisible(true);
        busca_codigo.grabFocus();// TODO add your handling code here:
    }//GEN-LAST:event_codigo_productoMouseClicked

    private void busca_todoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busca_todoKeyPressed
        jPproductos.setVisible(true);
        String[] titulos = {"codigo", "nombre", "precio", "stock"};
        String[] registros = new String[40];
        String sql = "SELECT *FROM productos WHERE nombre LIKE '%" + busca_todo.getText() + "%' "
                + "OR codigo LIKE '%" + busca_todo.getText() + "%'"
                + "OR precio LIKE '%" + busca_todo.getText() + "%'";

        model = new DefaultTableModel(null, titulos);
        conectarBD cc = new conectarBD();
        Connection conect = cc.conexion();
        try {
            Statement st = (Statement) conect.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("codigo");
                registros[1] = rs.getString("nombre");
                registros[2] = rs.getString("precio");
                registros[3] = rs.getString("stock");
                model.addRow(registros);
            }
            jTableProductos.setModel(model);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_busca_todoKeyPressed

    private void busca_todoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busca_todoMouseClicked
        limpia_busqueda();    // TODO add your handling code here:
    }//GEN-LAST:event_busca_todoMouseClicked

    private void grabar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabar1ActionPerformed

        hora_pedido.setText(jlbhora.getText());//covierte la hora de jlabel a jtextfile
        fecha_pedido.setText(jlbfecha.getText());
        if (subtotal.getText().equals("$SubT") || fecha_pedido.getText().equals("") || hora_pedido.getText().equals("") || filas.getText().equals("Nº Filas") || usuario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falta Completar Datos del Pedido", "No Se Puede Avanzar", 1);
        } else {
            // envia los registros de una tabla a otra tabla
            procesar_pago abrir = new procesar_pago();
            abrir.setVisible(true);

            for (int i = 0; i < jTableMesaConsumo.getRowCount(); i++) {
                String Datos[] = new String[7];
                Datos[0] = jTableMesaConsumo.getValueAt(i, 0).toString();
                Datos[1] = jTableMesaConsumo.getValueAt(i, 1).toString();
                Datos[2] = jTableMesaConsumo.getValueAt(i, 2).toString();
                Datos[3] = jTableMesaConsumo.getValueAt(i, 3).toString();
                Datos[4] = jTableMesaConsumo.getValueAt(i, 4).toString();
                Datos[5] = jTableMesaConsumo.getValueAt(i, 5).toString();
                Datos[6] = jTableMesaConsumo.getValueAt(i, 6).toString();

                procesar_pago.modelo2.addRow(Datos);

            }
            //pasar el contenido de un textFile a otra ventana
            String submonto = subtotal.getText();
            procesar_pago.txt_subtotal.setText(submonto);
            String montoTotal = subtotal.getText();
            procesar_pago.txt_total.setText(montoTotal);
            String fecha = fecha_pedido.getText();
            procesar_pago.fecha_pago.setText(fecha);
            String hora = hora_pedido.getText();
            procesar_pago.hora_pago.setText(hora);
            String num = filas.getText();
            procesar_pago.n_filas.setText(num);
            String name = usuario.getText();
            procesar_pago.id_usuario.setText(name);

        }
    }//GEN-LAST:event_grabar1ActionPerformed

    private void eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar1ActionPerformed

        int borra = jTableMesaConsumo.getSelectedRow();
        if (borra >= 0) {
            int eli = JOptionPane.showConfirmDialog(null, "Desea Borrar el Registro Seleccionado?", "Confirme Opción", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (eli == 0) {
                modelo.removeRow(borra);
                suma_montos();
                contar_filas();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione Algún Registro", "Debe Especificar", 1);
        }
    }//GEN-LAST:event_eliminar1ActionPerformed

    private void vaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaciarActionPerformed

        if (filas.getText().equals("") || filas.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "La Tabla Está Vacía", "No Hay Registros", 1);

        } else {
            int vac = JOptionPane.showConfirmDialog(null, "Desea Borrar Todos los Registros del Pedido?", "Confirme Opción", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (vac == 0) {
                subtotal.setText("");
                filas.setText("");
                int borrato = jTableMesaConsumo.getRowCount();
                for (int i = borrato - 1; i >= 0; i--) {
                    modelo.removeRow(i);
                }
            }

        }
    }//GEN-LAST:event_vaciarActionPerformed

    private void subeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subeActionPerformed
        sube.setVisible(false);
        baja.setVisible(true);
        jPanelSlider1.setVisible(true);
        jPanelSlider1.nextPanel(10, panel_open, jPanelSlider1.right);
    }//GEN-LAST:event_subeActionPerformed

    private void bajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaActionPerformed
        jPanelSlider1.setVisible(true);
        jPanelSlider1.nextPanel(10, panel_close, jPanelSlider1.left);
        baja.setVisible(false);
        sube.setVisible(true);
    }//GEN-LAST:event_bajaActionPerformed

    private void btn_administrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_administrarActionPerformed
        if (usuario_tipo.getText().equals("Invitado")) {
            JOptionPane.showMessageDialog(null, "Usted No Es Administrador", "Acceso Denegado", 0);
        } else {

            administrar abrir3 = new administrar();
            abrir3.setVisible(true);
            abrir3.toFront();
            abrir3.requestFocus();
            this.dispose();

            String name = usuario.getText();
            String tipe = usuario_tipo.getText();
            administrar.id_usuario.setText(name);
            administrar.tipo_usuario.setText(tipe);
        }
    }//GEN-LAST:event_btn_administrarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        int sal = JOptionPane.showConfirmDialog(null, "Desea Cerrar el Sistema?", "Confirme Opción", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (sal == 0) {
            Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this, Fade.EXIT);
        }
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stockActionPerformed

        agregar_stock abrir1 = new agregar_stock();
        abrir1.setVisible(true);

        String name = usuario.getText();
        agregar_stock.txt_usuario.setText(name);
    }//GEN-LAST:event_btn_stockActionPerformed

    private void btn_gastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gastarActionPerformed
        pagar_servicio abrir2 = new pagar_servicio();
        abrir2.setVisible(true);

        String name = usuario.getText();
        pagar_servicio.txt_usuario.setText(name);
    }//GEN-LAST:event_btn_gastarActionPerformed

    private void btn_devolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_devolucionActionPerformed
        reporte_ventas abrir2 = new reporte_ventas();
        abrir2.setVisible(true);
        abrir2.toFront();
        abrir2.requestFocus();
        this.dispose();

        String name = usuario.getText();
        reporte_ventas.id_usuario.setText(name);
    }//GEN-LAST:event_btn_devolucionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mozo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mozo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mozo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mozo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mozo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agrega_producto;
    private javax.swing.JButton baja;
    private javax.swing.JButton btn_administrar;
    private javax.swing.JButton btn_carta;
    private javax.swing.JButton btn_cerrars;
    private javax.swing.JButton btn_devolucion;
    private javax.swing.JButton btn_gastar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_stock;
    private javax.swing.JTextField busca_codigo;
    private javax.swing.JTextField busca_todo;
    private javax.swing.JTextField cantidad_producto;
    private javax.swing.JTextField codigo_producto;
    private javax.swing.JButton eliminar1;
    private javax.swing.JTextField fecha_pedido;
    private javax.swing.JLabel filas;
    private javax.swing.JButton grabar1;
    private javax.swing.JTextField hora_pedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider1;
    private javax.swing.JPanel jPconsumo;
    private javax.swing.JPanel jPproductos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMesaConsumo;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JLabel jlbfecha;
    private javax.swing.JLabel jlbhora;
    private javax.swing.JButton limpia_producto;
    private javax.swing.JTextField monto;
    private javax.swing.JTextField nombre_producto;
    private javax.swing.JPanel panel_close;
    private javax.swing.JPanel panel_open;
    private javax.swing.JTextField precio_producto;
    private javax.swing.JTextField stock_producto;
    private javax.swing.JButton sube;
    public static javax.swing.JLabel subtotal;
    public static javax.swing.JLabel usuario;
    public static javax.swing.JLabel usuario_tipo;
    private javax.swing.JButton vaciar;
    // End of variables declaration//GEN-END:variables
    // Crear la Conexxion a la BASE de Datos
    conectarBD cc = new conectarBD();
    Connection cn = cc.conexion();

}
