/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system2020;

import entidad.listaReporte;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import static system2020.mozo.subtotal;
import static system2020.procesar_pago.fecha_pago;
import static system2020.procesar_pago.txt_subtotal;

/**
 *
 * @author LENOVO
 */
public class reporte_ventas extends javax.swing.JFrame {

    Statement sent;
    DefaultTableModel model, modelo, modelVenta, modelD, modelBD;

    /**
     * Creates new form reporte_ventas
     */
    public reporte_ventas() {

        initComponents();
        cargarComboBD("");
        setLocationRelativeTo(null);
        this.setResizable(false);
        txt_fecha.setText(capturafechaAct());
        txt_fecha.setVisible(false);
        txt_producto.setVisible(false);
        jPanelDevolver.setVisible(false);
        jPanelDevueltos.setVisible(false);
        filas.setVisible(false); 
        fecha.setVisible(false);
        filas_ventas.setVisible(false);
        filas_devuelto.setVisible(false);
        btn_buscaDevuelto.setVisible(false);

        cargarVentas(txt_fecha.getText());

        btn_agregar.setEnabled(false);
        btn_devolver.setEnabled(false);
        btn_imprimir_ventas.setEnabled(false);

        // ir a Customize Code para crear el metodo que permite desactivar la edición de celdas, en Propiedades, TableHead están las opciones para modificar el tamaño de la celda y reordenar las columnas, en Propiedades, opción focusable para eliminar el borde que se marca al hacer click en la celda.
        modelo = new DefaultTableModel();// Crea columnas para tabla del reporte
        modelo.addColumn("Cantidad");
        modelo.addColumn("Producto");
        modelo.addColumn("Fecha");
        this.jTable_reportes.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jdt_fecha = new com.toedter.calendar.JDateChooser();
        cmbProducto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_buscaVenta = new javax.swing.JButton();
        txt_fecha = new javax.swing.JTextField();
        txt_producto = new javax.swing.JTextField();
        jonlyFecha = new javax.swing.JCheckBox();
        btn_buscaDevuelto = new javax.swing.JButton();
        lblsuma = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanelDevolver = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_cant = new javax.swing.JTextField();
        txt_prod = new javax.swing.JTextField();
        txt_fechV = new javax.swing.JTextField();
        txt_mont = new javax.swing.JTextField();
        txt_fechD = new javax.swing.JTextField();
        txt_vend = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_guardar_devolucion = new javax.swing.JButton();
        btn_cancelar_devolucion = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_deta = new javax.swing.JTextField();
        jPanelDevueltos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDevueltos = new javax.swing.JTable();
        btn_atras_dev = new javax.swing.JButton();
        filas_devuelto = new javax.swing.JTextField();
        jPanelVentas = new javax.swing.JPanel();
        btn_imprimir_ventas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ventas = new javax.swing.JTable();
        filas_ventas = new javax.swing.JTextField();
        lbl_monto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_reportes = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        btn_eliminar_registro_reporte = new javax.swing.JButton();
        btn_vaciar_registro_reporte = new javax.swing.JButton();
        filas = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btn_agregar = new javax.swing.JButton();
        btn_devolver = new javax.swing.JButton();
        btn_devoluciones = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        id_usuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Seleccione:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jdt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 58, 146, -1));

        cmbProducto.setBorder(null);
        jPanel1.add(cmbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 109, 146, -1));

        jLabel1.setText("Fecha:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 37, -1, -1));

        jLabel2.setText("Producto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 89, -1, -1));

        jLabel3.setText("Cantidad:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 140, -1, -1));

        btn_buscaVenta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_buscaVenta.setText("Buscar VE");
        btn_buscaVenta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btn_buscaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscaVentaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 100, 30));

        txt_fecha.setEnabled(false);
        txt_fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_fechaKeyReleased(evt);
            }
        });
        jPanel1.add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 70, -1));

        txt_producto.setEnabled(false);
        txt_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_productoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_productoKeyReleased(evt);
            }
        });
        jPanel1.add(txt_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 133, 70, -1));

        jonlyFecha.setText("Solo Fecha.");
        jonlyFecha.setFocusable(false);
        jPanel1.add(jonlyFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 33, 95, -1));

        btn_buscaDevuelto.setBackground(new java.awt.Color(255, 255, 255));
        btn_buscaDevuelto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_buscaDevuelto.setText("Buscar DE");
        btn_buscaDevuelto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscaDevueltoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscaDevuelto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 100, 30));

        lblsuma.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblsuma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblsuma.setFocusable(false);
        lblsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblsumaActionPerformed(evt);
            }
        });
        jPanel1.add(lblsuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 160, 60, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ventas:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelDevolver.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Devolver", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanelDevolver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Cantidad:");
        jPanelDevolver.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel5.setText("Producto:");
        jPanelDevolver.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 65, -1, -1));

        txt_cant.setEditable(false);
        txt_cant.setFocusable(false);
        jPanelDevolver.add(txt_cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 30, 100, -1));

        txt_prod.setEditable(false);
        txt_prod.setFocusable(false);
        jPanelDevolver.add(txt_prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 60, 100, -1));

        txt_fechV.setEditable(false);
        txt_fechV.setFocusable(false);
        jPanelDevolver.add(txt_fechV, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 100, -1));

        txt_mont.setEditable(false);
        txt_mont.setFocusable(false);
        jPanelDevolver.add(txt_mont, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 100, -1));

        txt_fechD.setEditable(false);
        txt_fechD.setFocusable(false);
        jPanelDevolver.add(txt_fechD, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 30, 100, -1));

        txt_vend.setEditable(false);
        txt_vend.setFocusable(false);
        jPanelDevolver.add(txt_vend, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 60, 100, -1));

        jLabel6.setText("Monto:");
        jPanelDevolver.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel7.setText("Fecha:");
        jPanelDevolver.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 65, -1, -1));

        jLabel8.setText("F.Devolución:");
        jPanelDevolver.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jLabel9.setText("Vendedor:");
        jPanelDevolver.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 65, 60, -1));

        btn_guardar_devolucion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_guardar_devolucion.setText("Aceptar");
        btn_guardar_devolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_devolucionActionPerformed(evt);
            }
        });
        jPanelDevolver.add(btn_guardar_devolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        btn_cancelar_devolucion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_cancelar_devolucion.setText("Cancelar");
        btn_cancelar_devolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_devolucionActionPerformed(evt);
            }
        });
        jPanelDevolver.add(btn_cancelar_devolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel10.setText("Detalles:");
        jPanelDevolver.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 105, -1, -1));
        jPanelDevolver.add(txt_deta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 180, -1));

        jPanel2.add(jPanelDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 630, 200));

        jPanelDevueltos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Devoluciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanelDevueltos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDevueltos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTableDevueltos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableDevueltos.setFocusable(false);
        jTableDevueltos.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableDevueltos);

        jPanelDevueltos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 570, 150));

        btn_atras_dev.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_atras_dev.setText("Regresar");
        btn_atras_dev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atras_devActionPerformed(evt);
            }
        });
        jPanelDevueltos.add(btn_atras_dev, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 180, -1, -1));

        filas_devuelto.setEditable(false);
        filas_devuelto.setFocusable(false);
        jPanelDevueltos.add(filas_devuelto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 40, -1));

        jPanel2.add(jPanelDevueltos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 18, 610, 220));

        jPanelVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_imprimir_ventas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_imprimir_ventas.setText("Imprimir");
        btn_imprimir_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimir_ventasActionPerformed(evt);
            }
        });
        jPanelVentas.add(btn_imprimir_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 185, 80, -1));

        jTable_ventas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_ventas.setFocusable(false);
        jTable_ventas.getTableHeader().setReorderingAllowed(false);
        jTable_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ventasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_ventas);

        jPanelVentas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 160));

        filas_ventas.setEditable(false);
        jPanelVentas.add(filas_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 30, -1));

        lbl_monto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_monto.setText("total $");
        jPanelVentas.add(lbl_monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        jPanel2.add(jPanelVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 620, 220));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Reporte:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTable_reportes = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable_reportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_reportes.setFocusable(false);
        jTable_reportes.getTableHeader().setReorderingAllowed(false);
        jTable_reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_reportesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_reportes);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Imprimir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btn_eliminar_registro_reporte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_eliminar_registro_reporte.setText("Eliminar");
        btn_eliminar_registro_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_registro_reporteActionPerformed(evt);
            }
        });

        btn_vaciar_registro_reporte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_vaciar_registro_reporte.setText("Vaciar");
        btn_vaciar_registro_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vaciar_registro_reporteActionPerformed(evt);
            }
        });

        filas.setEditable(false);

        fecha.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_vaciar_registro_reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_eliminar_registro_reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_vaciar_registro_reporte)
                    .addComponent(btn_eliminar_registro_reporte)
                    .addComponent(jButton4)
                    .addComponent(filas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        btn_agregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_agregar.setText("<AGREGAR>");
        btn_agregar.setMaximumSize(new java.awt.Dimension(105, 25));
        btn_agregar.setMinimumSize(new java.awt.Dimension(105, 25));
        btn_agregar.setPreferredSize(new java.awt.Dimension(105, 25));
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_devolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_devolver.setText("DEVOLVER");
        btn_devolver.setMaximumSize(new java.awt.Dimension(105, 25));
        btn_devolver.setMinimumSize(new java.awt.Dimension(105, 25));
        btn_devolver.setPreferredSize(new java.awt.Dimension(105, 25));
        btn_devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_devolverActionPerformed(evt);
            }
        });

        btn_devoluciones.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_devoluciones.setText("DEVUELTO");
        btn_devoluciones.setMaximumSize(new java.awt.Dimension(105, 25));
        btn_devoluciones.setMinimumSize(new java.awt.Dimension(105, 25));
        btn_devoluciones.setPreferredSize(new java.awt.Dimension(105, 25));
        btn_devoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_devolucionesActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("STOCK");
        jButton1.setMaximumSize(new java.awt.Dimension(105, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(105, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(105, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("ATRÁS");
        jButton7.setMaximumSize(new java.awt.Dimension(105, 25));
        jButton7.setMinimumSize(new java.awt.Dimension(105, 25));
        jButton7.setPreferredSize(new java.awt.Dimension(105, 25));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_devolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_devoluciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_devolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_devoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("_____________________________ VENTAS & DEVOLUCIONES _______________________________________");

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("__________________________________ LISTA GENERADA ____________________________________________");

        id_usuario.setFont(new java.awt.Font("Calibri", 2, 11)); // NOI18N
        id_usuario.setText("usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_usuario)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_usuario)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public float sumaMontoVenta() { // Suma el total de valores de una columna de un jTable
        int contar = jTable_ventas.getRowCount();
        float suma = 0;
        for (int i = 0; i < contar; i++) {
            // 3 -- cuarta columna
            suma = (suma + Float.parseFloat(jTable_ventas.getValueAt(i, 3).toString()));

        }
        return suma;
    }
      
    public int sumaCantidades() { // Suma el total de valores de una columna de un jTable
        int contar = jTable_ventas.getRowCount();
        int suma = 0;
        for (int i = 0; i < contar; i++) {
            // 1 -- segunda columna
            suma = suma + Integer.parseInt(jTable_ventas.getValueAt(i, 1).toString());

        }
        return suma;

    }

    public int sumaDevoluciones() { // Suma el total de valores de una columna de un jTable
        int contar = jTableDevueltos.getRowCount();
        int suma = 0;
        for (int i = 0; i < contar; i++) {
            // 1 -- segunda columna
            suma = suma + Integer.parseInt(jTableDevueltos.getValueAt(i, 1).toString());

        }
        return suma;

    }

    public static String capturafechaAct() { //metodo para capturar la fecha del sistema operativo
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YY");
        return formatoFecha.format(fecha);
    }

    public void cargarComboBD(String valor) { //Cargar a un combo box los datos de una columna desde una base de datos.
        try {

            String sql = "SELECT * FROM productos where codigo LIKE '%" + valor + "%' ";
            sent = cn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            while (rs.next()) {
                cmbProducto.addItem(rs.getString(2));

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void cargarVentas(String valor) {
        try {
            String[] titulos = {"ID", "Cantidad", "Producto", "Monto", "Codigo", "Hora", "Fecha", "Vendedor"};
            String[] registros = new String[40];
            String sql = "SELECT * FROM venta where fecha LIKE '%" + valor + "%' ";
            modelVenta = new DefaultTableModel(null, titulos);
            sent = cn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("id");
                registros[1] = rs.getString("cantidad");
                registros[2] = rs.getString("producto");
                registros[3] = rs.getString("monto");
                registros[4] = rs.getString("codigo");
                registros[5] = rs.getString("hora");
                registros[6] = rs.getString("fecha");
                registros[7] = rs.getString("vendedor");

                modelVenta.addRow(registros);
            }
            jTable_ventas.setModel(modelVenta);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void cargarDevoluciones(String valor) {
        try {
            String[] titulos = {"Producto", "Cantidad", "Monto", "F-Venta", "Vendedor", "F-Devolucion", "Detalles"};
            String[] registros = new String[7];
            String sql = "SELECT * FROM devoluciones where fechaVenta LIKE '%" + valor + "%' ";
            modelD = new DefaultTableModel(null, titulos);
            sent = cn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("producto");
                registros[1] = rs.getString("cantidad");
                registros[2] = rs.getString("monto");
                registros[3] = rs.getString("fechaVenta");
                registros[4] = rs.getString("vendedor");
                registros[5] = rs.getString("fechaDevolucion");
                registros[6] = rs.getString("detalles");

                modelD.addRow(registros);
            }
            jTableDevueltos.setModel(modelD);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void agregar() {
        String[] info = new String[3];
        info[0] = lblsuma.getText();
        info[1] = txt_producto.getText();
        info[2] = txt_fecha.getText();
        modelo.addRow(info);

    }

    public void limpiar() {
        txt_fecha.setText("");
        txt_producto.setText("");
        lblsuma.setText("");
        //jdt_fecha.setDate(null);
    }

    public void limpiar_devolver() {
        txt_cant.setText("");
        txt_mont.setText("");
        txt_prod.setText("");
        txt_fechV.setText("");
        txt_fechD.setText("");
        txt_vend.setText("");
        txt_deta.setText("");
    }

    public void ocultaDevolver() {
        txt_cant.setVisible(false);
        txt_mont.setVisible(false);
        txt_prod.setVisible(false);
        txt_fechV.setVisible(false);
        txt_fechD.setVisible(false);
        txt_vend.setVisible(false);
        txt_deta.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        btn_cancelar_devolucion.setVisible(false);
        btn_guardar_devolucion.setVisible(false);

    }

    public void ocultaDevueltos() {
        jTableDevueltos.setVisible(false);
    }

    private void btn_buscaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscaVentaActionPerformed
        txt_fecha.setText("");
        if (jdt_fecha.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Seleccione la FECHA de Venta", "aviso", 1);

            jdt_fecha.grabFocus();
        } else if (jonlyFecha.isSelected()) {
            SimpleDateFormat dformat = new SimpleDateFormat("dd/MM/YY");
            String date = dformat.format(jdt_fecha.getDate());
            txt_fecha.setText(date);

            cargarVentas(txt_fecha.getText());
            lblsuma.setText(Integer.toString(sumaCantidades()));
            lbl_monto.setText(Float.toString(sumaMontoVenta()));
            cargarDevoluciones(txt_fecha.getText());
            contar_filas_venta();

            btn_imprimir_ventas.setEnabled(true);

        } else if (cmbProducto.getSelectedItem().equals("")) {

            JOptionPane.showMessageDialog(null, "Seleccione el PRODUCTO Vendido", "aviso", 1);
        } else {                      //Pasa de un jDate a un TextFile
            SimpleDateFormat dformat = new SimpleDateFormat("dd/MM/YY");
            String date = dformat.format(jdt_fecha.getDate());
            txt_fecha.setText(date);

            String producto = cmbProducto.getSelectedItem().toString();
            txt_producto.setText(producto);

            String[] titulos = {"id", "cantidad", "producto", "monto", "codigo", "hora", "fecha", "vendedor"};
            String[] registros = new String[40];
            String sql = "SELECT *FROM venta WHERE fecha LIKE '%" + txt_fecha.getText() + "%' "
                    + "AND producto LIKE '%" + txt_producto.getText() + "%'";

            model = new DefaultTableModel(null, titulos);
            conectarBD cc = new conectarBD();
            Connection conect = cc.conexion();
            try {
                Statement st = (Statement) conect.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    registros[0] = rs.getString("id");
                    registros[1] = rs.getString("cantidad");
                    registros[2] = rs.getString("producto");
                    registros[3] = rs.getString("monto");
                    registros[4] = rs.getString("codigo");
                    registros[5] = rs.getString("hora");
                    registros[6] = rs.getString("fecha");
                    registros[7] = rs.getString("vendedor");
                    model.addRow(registros);
                }
                jTable_ventas.setModel(model);

                cargarDevoluciones(txt_fecha.getText());
                contar_filas_venta();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

            lblsuma.setText(Integer.toString(sumaCantidades())); // invoca el metodo que suma los valores de una columna
            btn_agregar.setEnabled(true);
            btn_imprimir_ventas.setEnabled(false);
        }

    }//GEN-LAST:event_btn_buscaVentaActionPerformed

    public void guardar_devolucion() {
        if (txt_deta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falta El Motivo de la Devolución");
            txt_deta.grabFocus();
        } else {
            String prod, cant, mont, fech1, vend, fech2, deta;
            String sql = "";
            prod = txt_prod.getText();
            cant = txt_cant.getText();
            mont = txt_mont.getText();
            fech1 = txt_fechV.getText();
            vend = txt_vend.getText();
            fech2 = txt_fechD.getText();
            deta = txt_deta.getText();

            sql = "INSERT INTO devoluciones(producto, cantidad, monto, fechaVenta, vendedor, fechaDevolucion, detalles) VALUES(?,?,?,?,?,?,?)";

            try {
                PreparedStatement pst = cn.prepareCall(sql);

                pst.setString(1, prod);
                pst.setString(2, cant);
                pst.setString(3, mont);
                pst.setString(4, fech1);
                pst.setString(5, vend);
                pst.setString(6, fech2);
                pst.setString(7, deta);
                int n = pst.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(null, "Devolución Realizada Exitosamente");
                }
                imprimir_devolucion();
            } catch (SQLException ex) {
                Logger.getLogger(mozo.class.getName()).log(Level.SEVERE, null, ex);
            }
            limpiar_devolver();
            jPanelDevolver.setVisible(false);
            jPanelDevueltos.setVisible(false);
            jPanelVentas.setVisible(true);
            btn_devoluciones.setEnabled(true);
        }
    }

    public void contar_filas() {
        for (int i = 0; i <= jTable_reportes.getRowCount(); i++) {
            filas.setText("" + i);
        }
    }

    public void contar_filas_venta() {
        for (int i = 0; i <= jTable_ventas.getRowCount(); i++) {
            filas_ventas.setText("" + i);
        }
    }

    public void contar_filas_devolucion() {
        for (int i = 0; i <= jTableDevueltos.getRowCount(); i++) {
            filas_devuelto.setText("" + i);
        }
    }

    public void imprimir_devolucion() {
        try {

            String master = System.getProperty("user.dir") + "/pdf/reportDevolucion.jasper";
            HashMap parametros = new HashMap();

            parametros.put("n_cantidad", txt_cant.getText());
            parametros.put("n_producto", txt_prod.getText());
            parametros.put("n_monto", txt_mont.getText());
            parametros.put("n_fechaV", txt_fechV.getText());
            parametros.put("n_fechaD", txt_fechD.getText());
            parametros.put("n_vendedor", txt_vend.getText());
            JasperPrint jp = JasperFillManager.fillReport(master, parametros, new JREmptyDataSource());
            JasperViewer.viewReport(jp, false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void reporte() { //no funciona hasta ahora

        List lista = new ArrayList();
        for (int i = 0; i < jTable_reportes.getRowCount(); i++) {
            listaReporte productos = new listaReporte(jTable_reportes.getValueAt(i, 0).toString(), jTable_reportes.getValueAt(i, 1).toString(), jTable_reportes.getValueAt(i, 2).toString());
            lista.add(productos);
        }
        JasperReport reporti;
        try {
            //String master = System.getProperty("user.dir") + "/pdf/reportProductos.jasper";
            reporti = (JasperReport) JRLoader.loadObjectFromFile("C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\System2020\\src\\reportLista.jasper");
            JasperPrint imprimir = JasperFillManager.fillReport(reporti, null, new JRBeanCollectionDataSource(lista));
            JasperViewer.viewReport(imprimir, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void txt_fechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fechaKeyReleased

    }//GEN-LAST:event_txt_fechaKeyReleased

    private void txt_productoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_productoKeyReleased

    }//GEN-LAST:event_txt_productoKeyReleased

    private void txt_productoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_productoKeyPressed

    }//GEN-LAST:event_txt_productoKeyPressed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        fecha.setText(txt_fecha.getText());
        agregar();
        limpiar();
        contar_filas();
        btn_agregar.setEnabled(false);
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void jTable_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ventasMouseClicked
        if (evt.getButton() == 1) {
            int pst = jTable_ventas.getSelectedRow();
            try {
                String sql = "SELECT * FROM venta where id= " + jTable_ventas.getValueAt(pst, 0).toString();
                sent = cn.createStatement();
                ResultSet rs = sent.executeQuery(sql);
                rs.next();
                txt_prod.setText(rs.getString("producto"));
                txt_cant.setText(rs.getString("cantidad"));
                txt_mont.setText(rs.getString("monto"));
                txt_fechV.setText(rs.getString("fecha"));
                txt_vend.setText(rs.getString("vendedor"));

                //busca_codigo.setText(rs.getString("codigo"));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            btn_devolver.setEnabled(true);
        }
    }//GEN-LAST:event_jTable_ventasMouseClicked

    private void btn_devolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_devolverActionPerformed
        jPanelDevolver.setVisible(true); //muestra devolucion
        jPanelVentas.setVisible(false); //oculta ventas
        jPanelDevueltos.setVisible(false);
        btn_devolver.setEnabled(false);
        txt_fechD.setText(capturafechaAct()); // muestra la fecha capturada
        txt_deta.grabFocus();
        btn_devoluciones.setEnabled(false);
    }//GEN-LAST:event_btn_devolverActionPerformed

    private void btn_cancelar_devolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_devolucionActionPerformed
        int sal = JOptionPane.showConfirmDialog(null, "Desea Cancelar La Devolución?", "Confirme Opción", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (sal == 0) {
            jPanelDevolver.setVisible(false);
            jPanelVentas.setVisible(true);
            btn_devolver.setEnabled(false);
            limpiar_devolver();
            btn_devoluciones.setEnabled(true);
        }
    }//GEN-LAST:event_btn_cancelar_devolucionActionPerformed

    private void btn_devolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_devolucionesActionPerformed
        cargarDevoluciones("");
        jPanelDevueltos.setVisible(true);
        jPanelVentas.setVisible(false);
        jPanelDevolver.setVisible(false);
        btn_devolver.setEnabled(false);
        btn_buscaVenta.setVisible(false);
        btn_buscaDevuelto.setVisible(true);

    }//GEN-LAST:event_btn_devolucionesActionPerformed

    private void btn_atras_devActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atras_devActionPerformed
        jPanelDevueltos.setVisible(false);
        jPanelDevolver.setVisible(false);
        jPanelVentas.setVisible(true);

        limpiar_devolver();
        btn_buscaVenta.setVisible(true);
        btn_buscaDevuelto.setVisible(false);

        jdt_fecha.setDate(null);
        lblsuma.setText("");
    }//GEN-LAST:event_btn_atras_devActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int sal = JOptionPane.showConfirmDialog(null, "Desea Cerrar esta Ventana?", "Confirme Opción", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (sal == 0) {
            mozo abrir1 = new mozo();
            abrir1.setVisible(true);
            abrir1.toFront();
            abrir1.requestFocus();
            this.dispose();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btn_guardar_devolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_devolucionActionPerformed
        guardar_devolucion();
    }//GEN-LAST:event_btn_guardar_devolucionActionPerformed

    private void jTable_reportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_reportesMouseClicked

    }//GEN-LAST:event_jTable_reportesMouseClicked

    private void btn_eliminar_registro_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_registro_reporteActionPerformed
        int borra = jTable_reportes.getSelectedRow();
        if (borra >= 0) {
            int eli = JOptionPane.showConfirmDialog(null, "Desea Borrar el Registro Seleccionado?", "Confirme Opción", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (eli == 0) {
                modelo.removeRow(borra);
                contar_filas();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione Algún Registro", "Debe Especificar", 1);
        }
    }//GEN-LAST:event_btn_eliminar_registro_reporteActionPerformed

    private void btn_vaciar_registro_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vaciar_registro_reporteActionPerformed
        if (filas.getText().equals("") || filas.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "La Tabla Está Vacía", "No Hay Registros", 1);

        } else {
            int vac = JOptionPane.showConfirmDialog(null, "Desea Borrar Todos los Registros del Pedido?", "Confirme Opción", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (vac == 0) {
                int borrato = jTable_reportes.getRowCount();
                for (int i = borrato - 1; i >= 0; i--) {
                    modelo.removeRow(i);
                    filas.setText("");
                }
            }

        }
    }//GEN-LAST:event_btn_vaciar_registro_reporteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (filas.getText().equals("") || filas.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "La Tabla Está Vacía", "Sin Registros Para IMPRIMIR", 1);

        } else {

            try {
                ArrayList<String> listado = new ArrayList<String>();
                String master = System.getProperty("user.dir") + "/pdf/report1.jasper";
                HashMap parametros = new HashMap();
                String v = "";
                for (int i = 0; i < jTable_reportes.getRowCount(); i++) {
                    listado.add(i,
                            jTable_reportes.getValueAt(i, 0)
                            + "  " + jTable_reportes.getValueAt(i, 1)
                            + "    " + jTable_reportes.getValueAt(i, 2));
                }
                for (int i = 0; i < listado.size(); i++) {
                    v = v + "\n" + listado.get(i);
                }
                JOptionPane.showMessageDialog(null, v);
                parametros.put("tablareport", v);
                parametros.put("n_filas", filas.getText());
                parametros.put("n_fecha", fecha.getText());
                JasperPrint jp = JasperFillManager.fillReport(master, parametros, new JREmptyDataSource());
                JasperViewer.viewReport(jp, false);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_imprimir_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimir_ventasActionPerformed
        if (filas_ventas.getText().equals("") || filas_ventas.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "La Tabla Está Vacía", "Sin Registros Para IMPRIMIR", 1);

        } else {

            try {
                JasperReport reporte = null;
                String path = "src\\reportVentaFecha.jasper";

                Map parametro = new HashMap();
                parametro.put("tablareport", txt_fecha.getText());
                parametro.put("importe", lbl_monto.getText());
                parametro.put ("n_productos", lblsuma.getText());

                reporte = (JasperReport) JRLoader.loadObjectFromFile(path);

                JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);
                JasperViewer view = new JasperViewer(jprint, false);
                view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                view.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(agregar_stock.class.getName()).log(Level.SEVERE, null, ex);
            }
            btn_imprimir_ventas.setEnabled(false);
        }
    }//GEN-LAST:event_btn_imprimir_ventasActionPerformed

    private void btn_buscaDevueltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscaDevueltoActionPerformed
        txt_fecha.setText("");
        if (jdt_fecha.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Seleccione la FECHA de Devolución", "aviso", 1);

            jdt_fecha.grabFocus();
        } else if (jonlyFecha.isSelected()) {
            SimpleDateFormat dformat = new SimpleDateFormat("dd/MM/YY");
            String date = dformat.format(jdt_fecha.getDate());
            txt_fecha.setText(date);

            cargarDevoluciones(txt_fecha.getText());
            lblsuma.setText(Integer.toString(sumaDevoluciones()));
            contar_filas_venta();

        } else if (cmbProducto.getSelectedItem().equals("")) {

            JOptionPane.showMessageDialog(null, "Seleccione el PRODUCTO Devuelto", "aviso", 1);
        } else {                      //Pasa de un jDate a un TextFile
            SimpleDateFormat dformat = new SimpleDateFormat("dd/MM/YY");
            String date = dformat.format(jdt_fecha.getDate());
            txt_fecha.setText(date);

            String producto = cmbProducto.getSelectedItem().toString();
            txt_producto.setText(producto);

            String[] titulos = {"Producto", "Cantidad", "Monto", "FechaVenta", "Vendedor", "FechaDevolucion", "Detalles"};
            String[] registros = new String[40];
            String sql = "SELECT *FROM devoluciones WHERE fechaVenta LIKE '%" + txt_fecha.getText() + "%' "
                    + "AND producto LIKE '%" + txt_producto.getText() + "%'";

            modelBD = new DefaultTableModel(null, titulos);
            conectarBD cc = new conectarBD();
            Connection conect = cc.conexion();
            try {
                Statement st = (Statement) conect.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    registros[0] = rs.getString("producto");
                    registros[1] = rs.getString("cantidad");
                    registros[2] = rs.getString("monto");
                    registros[3] = rs.getString("fechaVenta");
                    registros[4] = rs.getString("vendedor");
                    registros[5] = rs.getString("fechaDevolucion");
                    registros[6] = rs.getString("detalles");
                    modelBD.addRow(registros);
                }
                jTableDevueltos.setModel(modelBD);
                lblsuma.setText(Integer.toString(sumaDevoluciones()));
                contar_filas_venta();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

            lblsuma.setText(Integer.toString(sumaCantidades())); // invoca el metodo que suma los valores de una columna
        }
    }//GEN-LAST:event_btn_buscaDevueltoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        agregar_stock abrir1 = new agregar_stock();
        abrir1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblsumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblsumaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reporte_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reporte_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reporte_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reporte_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reporte_ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_atras_dev;
    private javax.swing.JButton btn_buscaDevuelto;
    private javax.swing.JButton btn_buscaVenta;
    private javax.swing.JButton btn_cancelar_devolucion;
    private javax.swing.JButton btn_devoluciones;
    private javax.swing.JButton btn_devolver;
    private javax.swing.JButton btn_eliminar_registro_reporte;
    private javax.swing.JButton btn_guardar_devolucion;
    private javax.swing.JButton btn_imprimir_ventas;
    private javax.swing.JButton btn_vaciar_registro_reporte;
    private javax.swing.JComboBox<String> cmbProducto;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField filas;
    private javax.swing.JTextField filas_devuelto;
    private javax.swing.JTextField filas_ventas;
    public static javax.swing.JLabel id_usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelDevolver;
    private javax.swing.JPanel jPanelDevueltos;
    private javax.swing.JPanel jPanelVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableDevueltos;
    public javax.swing.JTable jTable_reportes;
    private javax.swing.JTable jTable_ventas;
    private com.toedter.calendar.JDateChooser jdt_fecha;
    private javax.swing.JCheckBox jonlyFecha;
    private javax.swing.JLabel lbl_monto;
    private javax.swing.JTextField lblsuma;
    private javax.swing.JTextField txt_cant;
    private javax.swing.JTextField txt_deta;
    private javax.swing.JTextField txt_fechD;
    private javax.swing.JTextField txt_fechV;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_mont;
    private javax.swing.JTextField txt_prod;
    private javax.swing.JTextField txt_producto;
    private javax.swing.JTextField txt_vend;
    // End of variables declaration//GEN-END:variables
    conectarBD cc = new conectarBD();
    Connection cn = cc.conexion();
}
